/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.zst.chat.service;


public enum ClientType implements org.apache.thrift.TEnum {
  PC(1),
  AndriodPhone(2),
  AndriodPad(3),
  iPhone(4),
  iPad(5);

  private final int value;

  private ClientType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ClientType findByValue(int value) { 
    switch (value) {
      case 1:
        return PC;
      case 2:
        return AndriodPhone;
      case 3:
        return AndriodPad;
      case 4:
        return iPhone;
      case 5:
        return iPad;
      default:
        return null;
    }
  }
}
