/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.zst.chat.service;


public enum ErrorCode implements org.apache.thrift.TEnum {
  OK(0),
  NetError(1),
  UserNotExist(100),
  PasswordError(101),
  UserDisable(102),
  UserExist(103),
  UserOffline(200);

  private final int value;

  private ErrorCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ErrorCode findByValue(int value) { 
    switch (value) {
      case 0:
        return OK;
      case 1:
        return NetError;
      case 100:
        return UserNotExist;
      case 101:
        return PasswordError;
      case 102:
        return UserDisable;
      case 103:
        return UserExist;
      case 200:
        return UserOffline;
      default:
        return null;
    }
  }
}
